// models.js

class UserModel {
    userId;
    username;
    email;
    role;
    points;

    // userId is generated by Firebase and extracted from the token
    constructor(userId, username, email, role) {
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.role = role;
    }
}

class CleanupEventModel {
    eventId;
    title;
    location;
    date;
    organizerId;

    constructor(title, location, date, organizerId) {
        this.title = title;
        this.location = location;
        this.date = date;
        this.organizerId = organizerId;
    }
}

/* imageID is generated for each image uploaded by the user with userId, date, and time. That is the same name it is stored in local storage. */

class ImageModel {
    imageId;
    userId;
    category;
    latitude;
    longitude;
    date;

    constructor(imageId, userId, category, latitude, longitude, date) {
        this.imageId = imageId;
        this.userId = userId;
        this.category = category;
        this.latitude = latitude;
        this.longitude = longitude;
        this.date = date;
    }
}

class EducationalContentModel {
    constructor(title, content, createdAt, updatedAt) {
        this.title = title;
        this.content = content;
    }
}

module.exports = {
    UserModel,
    CleanupEventModel,
    ImageModel,
    EducationalContentModel
};
